[build]
  command   = "npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redireciona rotas SPA para o Next.js handler
[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/___netlify-handler"
  status = 200
